{{- if and .Values.llamastack.enabled .Values.llamastack.route.enabled }}
---
apiVersion: route.openshift.io/v1
kind: Route
metadata:
  name: llamastack-rhoai-service
  namespace: {{ include "agentic-claims-demo.namespace" . }}
  labels:
    {{- include "agentic-claims-demo.labels" . | nindent 4 }}
    app: llamastack
spec:
  {{- if .Values.llamastack.route.host }}
  host: {{ .Values.llamastack.route.host }}
  {{- else }}
  host: {{ include "llamastack_route_prefix" . }}.{{ .Values.global.clusterDomain }}
  {{- end }}
  to:
    kind: Service
    name: llamastack-rhoai-service
    weight: 100
  port:
    targetPort: http
  {{- if .Values.llamastack.route.tls.enabled }}
  tls:
    termination: edge
    insecureEdgeTerminationPolicy: Redirect
  {{- end }}
  wildcardPolicy: None
{{- end }}
