{{- if and .Values.backend.enabled }}
---
apiVersion: v1
kind: ConfigMap
metadata:
  annotations:
    argocd.argoproj.io/sync-wave: "1"
  labels:
    {{- include "multi-agents.labels" . | nindent 4 }}
  name: init-backend
  namespace: {{ include "multi-agents.namespace" . }}
data:
{{ (.Files.Glob "files/cm.init-backend/*").AsConfig | indent 2 }}
{{- end }}
