apiVersion: v1
kind: ConfigMap
metadata:
  annotations:
    argocd.argoproj.io/sync-wave: '1'
  name: job-hibernate
  namespace: claims-demo
data:
  shutdown.sh: '#!/bin/bash


    set -e


    oc annotate inferenceservice/llama serving.kserve.io/stop=true --overwrite=true

    oc annotate inferenceservice/gemma serving.kserve.io/stop=true --overwrite=true

    oc scale sts/postgresql --replicas=0

    oc scale deploy/backend --replicas=0

    oc scale deploy/frontend --replicas=0

    oc scale deploy/rag-server --replicas=0

    '
  wakeup.sh: '#!/bin/bash


    set -e


    oc annotate inferenceservice/llama serving.kserve.io/stop=false --overwrite=true

    oc annotate inferenceservice/gemma serving.kserve.io/stop=false --overwrite=true

    oc scale sts/postgresql --replicas=1

    oc scale deploy/backend --replicas=1

    oc scale deploy/frontend --replicas=2

    oc scale deploy/rag-server --replicas=1

    '
