{{- if .Values.gptoss.enabled }}
---
apiVersion: v1
kind: Namespace
metadata:
  name: {{ include "gptoss.namespace" . }}
  labels:
    {{- include "multi-agents.labels" . | nindent 4 }}
    opendatahub.io/dashboard: "true"
  annotations:
    "helm.sh/hook": pre-install,pre-upgrade
    "helm.sh/hook-weight": "-100"
    "helm.sh/hook-delete-policy": before-hook-creation
    "argocd.argoproj.io/sync-wave": "-100"
{{- end }}
